factory/factory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('turnoverZNQ.urls')),
    path('update/', include('update.urls')),
    path('admin/', admin.site.urls),
    path('websocket/', include('websocket.urls')),
]

factory/login/urls.py
# encoding: utf-8

"""
File: urls.py
Author: Rock Johnson
"""
from django.urls import path

app_name = 'login'
urlpatterns = [
    path(),
]

factory/turnoverZNQ/urls.py
# encoding: utf-8

"""
File: urls.py
Author: Rock Johnson
"""
from django.urls import path
from . import views

app_name = 'turnoverZNQ'
urlpatterns=[
    path('', views.index, name='index'),
    path('page/<int:page>/', views.product, name='product'),
    path('page/<int:page>/search/<str:query>/', views.product, name='product_sear'),
    path('detail/<int:product_id>/page/<int:page>/', views.detail, name='detail'),
    path('detail/<int:product_id>/page/<int:page>/search/<str:query>/', views.detail, name='detail_sear'),
    path('product/add/', views.product_add, name='product_add'),
    path('product/delete/', views.product_del, name='product_del'),
    path('product/change/', views.product_change, name='product_change'),
    path('detail/<int:product_id>/add/', views.detail_add, name='detail_add'),
    path('search/', views.search, name='search'),
    path('page/change/', views.page_change, name='page_change'),
]

factory/update/urls.py
# encoding: utf-8

"""
File: urls.py
Author: Rock Johnson
"""
from django.urls import path
from . import views

app_name = 'update'
urlpatterns = [
    path('update/', views.update, name='update'),
]

factory/turnoverZNQ/models.py
from django.db import models

from login.models import User


class Product(models.Model):
    factory_name = models.CharField(max_length=50, blank=True, verbose_name='厂家')
    product_type = models.CharField(max_length=50, verbose_name='型号')
    product_name = models.CharField(max_length=50, blank=True, verbose_name='名称')
    product_default = models.IntegerField(default=0, blank=True, verbose_name='期初')
    product_now = models.IntegerField(default=0, blank=True, verbose_name='现存')
    product_in = models.IntegerField(default=0, blank=True, verbose_name='入库合计')
    product_out = models.IntegerField(default=0, blank=True, verbose_name='领料合计')
    is_delete = models.IntegerField(default=0, blank=True, verbose_name='是否删除')
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='用户id')

    def __str__(self):
        return self.product_type

    def data_is_normal(self):
        return self.product_now == self.product_default + self.product_in - self.product_out

    def is_del(self):
        return False if self.is_delete == 0 else True

    def has_same_product(self):
        products = Product.objects.all()
        for product in products:
            if self.id != product.id and self.factory_name == product.factory_name and \
                    self.product_type == product.product_type and self.product_name == product.product_name:
                return True
        return False

    is_del.admin_order_field = 'factory_name'
    is_del.boolean = True
    is_del.short_description = '是否删除?'


class Detail(models.Model):
    bill_id = models.CharField(max_length=50, null=True, verbose_name='批次号')
    operate = models.CharField(max_length=10, verbose_name='操作')
    operate_num = models.IntegerField(verbose_name='数量')
    time = models.DateField(verbose_name='日期')
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, verbose_name='产品id')

    def __str__(self):
        return self.bill_id


class ProductLave(models.Model):
    amount = models.IntegerField(verbose_name='数量')
    detail = models.ForeignKey(Detail, on_delete=models.DO_NOTHING, verbose_name='明细id')


class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='用户id')
    detail = models.ForeignKey(Detail, on_delete=models.DO_NOTHING, null=True, verbose_name='明细id')
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, null=True, verbose_name='产品id')
    operate = models.CharField(max_length=10, default=None, verbose_name='操作方式')
    log_time = models.DateTimeField(auto_now=True, verbose_name='操作时间')

factory/turnoverZNQ/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseNotFound, HttpResponse
from django.core.paginator import Paginator
from django.core.cache import cache
from django.db import transaction
from django.db.models import Q
from django.urls import reverse
from django.utils.timezone import now
import json

from login.models import User

def index(request):
    return redirect(reverse('turnoverZNQ:product', args=(1,)))

def search(request):
    urlname = request.POST.get('urlname')
    query = request.POST.get('query')
    product_id = request.POST.get('product_id')
    url = reverse('turnoverZNQ:product_sear', args=(1,query)) if urlname == 'product' else reverse('turnoverZNQ:detail_sear', args=(product_id, 1,query))
    return redirect(url)

def page_treat(cur_page, page_num):
    # 处理分页按钮
    res = page_num
    for i in res:
        if len(page_num) < 6:
            break
        if i == 1 or i == page_num[-1]:
            continue
        if cur_page > len(page_num) - 3:
            if i < page_num[-4]:
                res[i - 1] = None
            else:
                continue
        if i and cur_page <= 2 and i > 4:
            res[i - 1] = None
        elif cur_page > 2 and i != cur_page and i != cur_page - 1 and i != cur_page + 1:
            res[i - 1] = None
    return res

def base_page(model, page):
    # 通用的分页方法
    next_page = None
    prev_page = None
    page_size = cache.get_or_set('page_size', 10, None)

    if page_size == 'all':
        return {'page_lst': model, 'page_size': page_size}

    paginator = Paginator(model, page_size)
    if page > paginator.num_pages + 1:
        return None

    page_lst = paginator.page(page)
    page_num = page_treat(page, [i for i in range(1, paginator.num_pages + 1)])

    # 获取上一页和下一页
    if page_lst.has_next():
        next_page = page + 1
    if page_lst.has_previous():
        prev_page = page - 1

    return {'page_lst': page_lst, 'cur_page': page, 'prev_page': prev_page, 'next_page': next_page, 'page_num': page_num, 'page_size': page_size}

def product(request, page=1, query=None):
    # 产品的视图
    products = User.objects.get(user_name='Rock').product_set.filter(is_delete=0).order_by('product_name') if not query else \
        User.objects.get(user_name='Rock').product_set.filter(Q(is_delete=0), Q(factory_name__contains=query) |
                                                              Q(product_type__contains=query) |
                                                              Q(product_name__contains=query)).order_by('product_name')
    res = base_page(products, page)
    if query:
        res['query'] = query
    return render(request, 'turnoverZNQ/index.html', res) if res else HttpResponseNotFound()

def detail(request, product_id, page=1, query=None):
    # 某产品的流水明细
    products = get_object_or_404(User.objects.get(user_name='Rock').product_set, pk=product_id)
    details = products.detail_set.order_by('-time') if not query else products.detail_set.filter(time__contains=query).order_by('-time')
    res = base_page(details, page)
    if res:
        res['product_id'] = product_id
    if query:
        res['query'] = query
    return render(request, 'turnoverZNQ/detail.html', res) if res else HttpResponseNotFound()

def product_add(request):
    # 添加产品
    args = json.loads(request.GET.get('args'))
    try:
        User.objects.get(user_name='Rock').product_set.get(factory_name=args['factory'], product_type=args['id'], product_name=args['name'])
        res = 'duplicate'
    except:
        # 是没有重复的产品
        try:
            with transaction.atomic():
                product = User.objects.get(user_name='Rock').product_set.create(factory_name=args['factory'], product_type=args['id'], product_name=args['name'],
                                                      product_default=args['first'], product_now=args['now'], product_in=args['in'],
                                                      product_out=args['out'])
                User.objects.get(user_name='Rock').log_set.create(log_time=now(), product_id=product.id, operate='添加产品')
        except:
            res = 'err'
        res = 'ok'
    return HttpResponse(res)

def product_del(request):
    # 删除产品
    product_id = request.GET.get('id')
    res = 'ok'
    try:
        with transaction.atomic():
            User.objects.get(user_name='Rock').product_set.filter(id=product_id).update(is_delete=1)
            User.objects.get(user_name='Rock').log_set.create(log_time=now(), product_id=product_id, operate='删除产品')
    except:
        res = 'err'
    return HttpResponse(res)

def product_change(request):
    # 修改产品
    product_id = request.GET.get('id')
    data = json.loads(request.GET.get('datas'))
    res = 'ok'
    try:
        with transaction.atomic():
            p = User.objects.get(user_name='Rock').product_set.filter(id=product_id)
            if data.get('factory'):
                p.update(factory_name=data['factory'])
            elif data.get('id'):
                p.update(product_type=data['id'])
            elif data.get('name'):
                p.update(product_name=data['name'])
            elif data.get('first'):
                p.update(product_default=data['first'])
                p.update(product_now=p[0].product_default + p[0].product_in - p[0].product_out)
            User.objects.get(user_name='Rock').log_set.create(log_time=now(), product_id=product_id, operate='修改产品')
            if p[0].has_same_product():
                raise BaseException('duplicate')
    except BaseException:
        res = 'duplicate'
    except:
        res = 'err'
    return HttpResponse(res)

def detail_add(request, product_id):
    # 添加流水账明细
    args = json.loads(request.GET.get('args'))
    try:
        with transaction.atomic():
            product = User.objects.get(user_name='Rock').product_set.get(id=product_id)

            if args['operate'] == "入库":
                product.product_in += args['num']
                detail = product.detail_set.create(bill_id=args['bill_id'], operate=args['operate'],
                                                   operate_num=args['num'], time=args['time'])
                detail.productlave_set.create(amount=args['num'])
            else:
                # 领料操作
                if args['num'] > product.product_now:
                    return HttpResponse('big')

                product.product_out += args['num']
                products = list(product.detail_set.filter(operate='入库').order_by('-time'))
                if len(products) > 0:
                    for i in products[:]:
                        first_product = products.pop().productlave_set.all()[0]
                        if first_product.amount == 0:
                            continue
                        if first_product.amount < args['num']:
                            args['num'] -= first_product.amount # 操作产品数量
                            detail = product.detail_set.create(bill_id=first_product.detail.bill_id, operate=args['operate'],
                                                               operate_num=first_product.amount, time=args['time'])
                            first_product.amount = 0
                            first_product.save()
                            continue

                        detail = product.detail_set.create(bill_id=first_product.detail.bill_id, operate=args['operate'],
                                                           operate_num=args['num'], time=args['time'])
                        first_product.amount -= args['num']
                        first_product.save()
                        args['num'] = 0
                        break
                else:
                    detail = product.detail_set.create(operate=args['operate'], operate_num=args['num'], time=args['time'])

            product.product_now = product.product_default + product.product_in - product.product_out
            product.save()

            User.objects.get(user_name='Rock').log_set.create(log_time=now(), detail_id=detail.id, operate=args['operate'])
        res = 'ok'
    except:
        res = 'err'
    return HttpResponse(res)

def page_change(request):
    # 修改每页显示的数量
    page_size = request.GET.get('page_size')
    res = 'ok'
    if page_size != 'all':
        try:
            page_size = int(page_size)
        except:
            res = 'err'
    cache.set('page_size', page_size, None)
    return HttpResponse(res)

factory/turnoverZNQ/templates/turnoverZNQ/base.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'turnoverZNQ/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'turnoverZNQ/css/nav.css' %}">
    <link rel="stylesheet" href="{% static 'turnoverZNQ/css/search-form.css' %}">
{% endblock %}
{% block content %}
    <div class="header">
        <div class="wrap">
            <div class="dataTablesInfo"  role="status" aria-live="polite">
                {% block botton %}<a href="{% url 'turnoverZNQ:index' %}"><button class="showDatasBtn">返回主页</button></a>{% endblock %}
            </div>

            <!--更新按钮-->
            <div class="tablesUpdate"  role="status" aria-live="polite">
                <button class="showDatasBtn" onclick="update('{% url 'update:update' %}')">更新软件</button>
            </div>

            <!--动态搜索框-->
            <section class="container">
                <form style="position: relative" method="post" action="{% url 'turnoverZNQ:search' %}" onsubmit="submitFn(this, event);">
                    {% csrf_token %}
                    <div class="search-wrapper">
                        {% block search_hide %}<input type="hidden" name="urlname" value="product">{% endblock %}
                        <div class="input-holder">
                            <input type="text" name="query" class="search-input" placeholder="格式: {% block search_place %}厂家&型号&名称{% endblock %}" />
                            <button class="search-icon" onclick="searchToggle(this, event);"><span></span></button>
                        </div>
                        <span class="close" onclick="searchToggle(this, event);"></span>
                    </div>
                </form>
            </section>
        </div>
    </div>
    <div>
        <div class="digital">
            <!-- 中间表格部分  S-->
            <table width="100%" id="userImportTable" border="0" cellpadding="0" cellspacing="0">
                <thead>
                    {% block thead %}{% endblock %}
                </thead>
                <tbody>{% block tbody %}{% endblock %}</tbody>
                <tfoot>
                    <tr>
                        <th colspan="8" height="30">
                            <div class="userImportTableBottom">
                                <!--可选择每页暂时数据条数-->
                                <div class="digitalLength" >
                                    <label>每页显示
                                        <select name="tablesLength" class="tablesLength" onchange="changePages(this.value)">
                                            <option {% if page_size == 10 %}selected="selected"{% endif %} value="10">10</option>
                                            <option {% if page_size == 15 %}selected="selected"{% endif %} value="15">15</option>
                                            <option {% if page_size == 20 %}selected="selected"{% endif %} value="20">20</option>
                                            <option {% if page_size == 'all' %}selected="selected"{% endif %} value="all">全部</option>
                                        </select>
                                    </label>
                                </div>

                                <!--显示页码数，前翻页，后翻页，当前页码-->
                                {% url 'turnoverZNQ:product' prev_page as prev_url %}
                                {% url 'turnoverZNQ:product' next_page as next_url %}
                                {% if query %}
                                    {% url 'turnoverZNQ:product_sear' prev_page query as prev_url %}
                                    {% url 'turnoverZNQ:product_sear' next_page query as next_url %}
                                {% endif %}
                                <div class=" tablePageinate">
                                    {% if prev_page %}
                                        <a href="{% block prev_href %}{{ prev_url }}{% endblock %}" class="pageinateBtn previous">&lt;</a>
                                    {% else %}
                                        <a href="javascript:;" class="pageinateBtn previous disabled">&lt;</a>
                                    {% endif %}

                                    {% for page in page_num %}
                                        {% if page %}
                                            {% url 'turnoverZNQ:product' page as cur_url %}
                                            {% if query %}
                                                {% url 'turnoverZNQ:product_sear' page query as cur_url %}
                                            {% endif %}
                                            <span class="pageBtnS">
                                                <a href="{% block page_href %}{{ cur_url }}{% endblock %}"
                                                   class="pageinateBtn{% if page == cur_page %} current{% endif %}">{{ page }}</a>
                                            </span>
                                        {% endif %}
{#                                        <span class="nextEllipsis">...</span>#}
                                    {% endfor %}

                                    {% if next_page %}
                                        <a href="{% block next_href %}{{ next_url }}{% endblock %}" class="pageinateBtn next">&gt;</a>
                                    {% else %}
                                        <a href="javascript:;" class="pageinateBtn next disabled">&gt;</a>
                                    {% endif %}
                                </div>
                            </div>
                        </th>
                    </tr>
                </tfoot>
            </table>
            <!-- 中间表格部分  E-->
        </div>
    </div>

    <!--模态窗口-->
    {% block modal %}{% endblock %}

    <!--返回顶部-->
    <div class="leftNav-item">
		<ul>
			<li title="返回顶部" class="for-top">
				<i class="fa fa-arrow-up"></i>
				<a href="javascript:;" class="rota">去顶部</a>
			</li>
		</ul>
	</div>
{% endblock %}
{% block script %}
    <script src="{% static 'turnoverZNQ/js/data.js' %}"></script>
    <script src="{% static 'turnoverZNQ/js/table.js' %}"></script>
    <script src="{% static 'turnoverZNQ/js/rmodal.js' %}"></script>
    <script src="{% static 'turnoverZNQ/js/nav.js' %}"></script>
    <script src="{% static 'turnoverZNQ/js/searchBar.js' %}"></script>
    <script>loadModal();</script>
{% endblock %}

factory/turnoverZNQ/templates/turnoverZNQ/detail.html
{% extends 'turnoverZNQ/base.html' %}
{% block title %}流水账明细{% endblock %}
{% block thead %}
    <tr>
        <th>厂家</th>
        <th>型号</th>
        <th>名称</th>
        <th>批次号</th>
        <th>操作</th>
        <th>数量</th>
        <th>日期</th>
    </tr>
{% endblock %}

{% block search_hide %}
    <input type="hidden" name="urlname" value="detail">
    <input type="hidden" name="product_id" value="{{ product_id }}">
{% endblock %}
{% block search_place %}年-月-日{% endblock %}

{% block tbody %}
    {% for detail in page_lst %}
        <tr>
            <td>{{ detail.product.factory_name|default:'空' }}</td>
            <td>{{ detail.product.product_type }}</td>
            <td>{{ detail.product.product_name }}</td>
            <td>{{ detail.bill_id|default:'空' }}</td>
            <td>{{ detail.operate }}</td>
            <td>{{ detail.operate_num }}</td>
            <td>{{ detail.time|date:'Y-m-d' }}</td>
        </tr>
    {% empty %}
        <tr><td colspan="7"><div class="reminder"><p>没有检索到数据</p></div></td></tr>
    {% endfor %}
{% endblock %}

{% url 'turnoverZNQ:detail' product_id prev_page as prev_url %}
{% url 'turnoverZNQ:detail' product_id next_page as next_url %}
{% if query %}
    {% url 'turnoverZNQ:detail_sear' product_id prev_page query as prev_url %}
    {% url 'turnoverZNQ:detail_sear' product_id next_page query as next_url %}
{% endif %}
{% block prev_href %}{{ prev_url }}{% endblock %}
{% block page_href %}
    {% if query %}
        {% url 'turnoverZNQ:detail_sear' product_id page query %}
    {% else %}
        {% url 'turnoverZNQ:detail' product_id page %}
    {% endif %}
{% endblock %}
{% block next_href %}{{ next_url }}{% endblock %}

factory/turnoverZNQ/templates/turnoverZNQ/index.html
{% extends 'turnoverZNQ/base.html' %}
{% block title %}流水账{% endblock %}
{% block thead %}
    <tr>
        <th>厂家{{ test }}</th>
        <th>型号</th>
        <th>名称</th>
        <th>期初</th>
        <th>现存</th>
        <th>入库合计</th>
        <th>领料合计</th>
        <th><span title="切换操作" style="cursor: pointer" onclick="operatToggle()">操作</span></th>
    </tr>
{% endblock %}

{% block botton %}
    {% if query %}
        <a href="{% url 'turnoverZNQ:index' %}"><button class="showDatasBtn">返回主页</button></a>
    {% else %}
        <button class="showDatasBtn" onclick="addDatas()">添加产品</button>
    {% endif %}
{% endblock %}

{% block tbody %}
    {% for pro in page_lst %}
        <tr _id="{{ pro.id }}">
            <td style='cursor: pointer' ondblclick='changeDatas($(this), "factory")'>{{ pro.factory_name|default:'空' }}</td>
            <td style='cursor: pointer' ondblclick='changeDatas($(this), "id")'><a href="{% url 'turnoverZNQ:detail' pro.id 1 %}">{{ pro.product_type }}</a></td>
            <td style='cursor: pointer' ondblclick='changeDatas($(this), "name")'>{{ pro.product_name }}</td>
            <td style='cursor: pointer' ondblclick='changeDatas($(this), "first")'>{{ pro.product_default }}</td>
            <td>{{ pro.product_now }}</td>
            <td>{{ pro.product_in }}</td>
            <td>{{ pro.product_out }}</td>
            <td>
                <button class='checkBtn showModal'>入库</button>
                <button {% if pro.product_now <= 0 %}disabled="disabled"{% endif %} class='checkBtn showModal ml'>领料</button>
            </td>
        </tr>
    {% empty %}
        <tr><td colspan="8"><div class="reminder"><p>没有检索到数据</p></div></td></tr>
    {% endfor %}
{% endblock %}

{% block modal %}
    <div id="modal" class="modal">
        <div class="modal-dialog animated">
            <div class="modal-content">
                <form class="form-horizontal" method="get">
                    <div class="modal-header">
                        <strong></strong>
                    </div>

                    <div class="modal-body">
                        <div class="form-group">
                            <div class="input-group col-xs-7 mb">
                                <input placeholder="批次号..." type="text" name="keys" class="form-control" />
                            </div>
                            <div class="input-group col-xs-7 mb">
                                <input placeholder="数量..." type="text" name="amounts" class="form-control" />
                            </div>
                            <div class="input-group col-xs-7">
                                <input placeholder="时间: m-d" type="text" name="dates" class="form-control" />
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-default" type="button" onclick="modal.close(0);">取消</button>
                        <button class="btn btn-primary" type="button" onclick="modal.close(1);">确认</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}