factory/factory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('turnoverZNQ.urls')),
    path('update/', include('update.urls')),
    path('admin/', admin.site.urls),
    path('websocket/', include('websocket.urls')),
]

factory/login/urls.py
# encoding: utf-8

"""
File: urls.py
Author: Rock Johnson
"""
from django.urls import path

app_name = 'login'
urlpatterns = [
    path(),
]

factory/websocket/urls.py
# encoding: utf-8

"""
File: urls.py
Author: Rock Johnson
"""
from django.urls import path
from . import views

app_name = 'websocket'
urlpatterns = [
    path('', views.index, name='index'),
    path('socket/', views.socket, name='socket'),
]

factory/websocket/models.py
from django.db import models

# Create your models here.

factory/websocket/views.py
import threading, time
from django.shortcuts import render
from dwebsocket.decorators import accept_websocket



def index(request):
    return render(request, 'websocket/index.html')

clients = []

@accept_websocket
def socket(request):
    if request.is_websocket:
        lock = threading.RLock()
        try:
            lock.acquire()
            clients.append(request.websocket)
            for message in request.websocket:
                if not message:
                    break
                for client in clients:
                    client.send(('%s %d号用户: %s' % (time.strftime('%Y-%m-%d %H:%M:%S'), clients.index(request.websocket) + 1, message.decode())).encode())
        finally:
            clients.remove(request.websocket)
            lock.release()

factory/websocket/templates/websocket/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>即时通讯</title>
</head>
<body>
    <input type="text" id="message" value="Hello, World" />
    <button id="connect_websocket">连接websocket</button>
    <button id="send_message">发送消息</button>
    <button id="close_websocket">关闭websocket</button>
    <h1></h1>
    <div id="messagecontainer"></div>

    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script>
        $(function () {
            $('#connect_websocket').click(function () {
                if(window.s){
                    window.s.close()
                }

                let s = new WebSocket('ws://' + window.location.host + '{% url 'websocket:socket' %}');
                s.onopen = function () {
                    console.log('WebSocket已打开')
                };
                s.onmessage = function (e) {
                    console.log('消息: ' + e.data);
                    $('#messagecontainer').prepend('<p>' + e.data + '</p>');
                };

                window.s = s;
            });

            $('#send_message').click(function () {
                if(!window.s){
                    alert('请连接服务')
                }else{
                    window.s.send($('#message').val());
                }
            });

            $('#close_websocket').click(function () {
                if(window.s){
                    window.s.close();
                }
            });
        })
    </script>
</body>
</html>